name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Run build script for macOS
      run: |
        bash -v -e ./install-on-mac-os.sh
      env:
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
