name: CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [macOS-10.12, macOS-10.13, macOS-10.14]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Run build script for macOS Sierra
      run: |
        bash -v -e ./install-on-mac-os-sierra.sh
      env:
        SVN: ${{ secrets.SVN }}
        SVN_ICECUBE_USERNAME: icecube
        SVN_ICECUBE_PASSWORD: ${{ secrets.SVN_ICECUBE_PASSWORD }}
